### ISSUE TITLE
assertion 'GTK_IS_WINDOW (window)' failed

### ISSUE THREAD

**Issue by 21st-centuryman** [randomplum/homebrew-gtkwave#2] opened 2023-10-03 12:55 UTC
Hello, I was your thread [here](https://github.com/gtkwave/gtkwave/issues/250) and saw you asked for feedback regarding the gtkwave homebrew port you are working on.

I am having issues where it seems to not install as a cask properly, mainly it seems to be installed as a formulae. 
```
$ brew install -v --cask randomplum/gtkwave/gtkwave
==> Tapping randomplum/gtkwave
git clone https://github.com/randomplum/homebrew-gtkwave /opt/homebrew/Library/Taps/randomplum/homebrew-gtkwave --origin=origin --template= --config core.fsmonitor=false
Cloning into '/opt/homebrew/Library/Taps/randomplum/homebrew-gtkwave'...
remote: Enumerating objects: 23, done.
remote: Counting objects: 100% (23/23), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 23 (delta 12), reused 16 (delta 8), pack-reused 0
Receiving objects: 100% (23/23), 5.79 KiB | 5.79 MiB/s, done.
Resolving deltas: 100% (12/12), done.
Tapped 1 formula (16 files, 19KB).
Warning: Cask 'gtkwave' is unavailable: '/opt/homebrew/Library/Taps/randomplum/homebrew-gtkwave/Casks/gtkwave.rb' does not exist.
==> Searching for similarly named casks...
==> Downloading https://formulae.brew.sh/api/cask.jws.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
==> Casks
gtkwave

To install gtkwave, run:
  brew install --cask gtkwave
 ```
 If i install it successfully, ie with --HEAD i get the following
 ```
 $ brew install --HEAD randomplum/gtkwave/gtkwave
==> Tapping randomplum/gtkwave
Cloning into '/opt/homebrew/Library/Taps/randomplum/homebrew-gtkwave'...
remote: Enumerating objects: 23, done.
remote: Counting objects: 100% (23/23), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 23 (delta 12), reused 16 (delta 8), pack-reused 0
Receiving objects: 100% (23/23), 5.79 KiB | 5.79 MiB/s, done.
Resolving deltas: 100% (12/12), done.
Tapped 1 formula (16 files, 19KB).
==> Fetching randomplum/gtkwave/gtkwave
==> Downloading https://raw.githubusercontent.com/randomplum/homebrew-gtkwave/main/macos_compat.diff
######################################################################################################################################################################################################################################################### 100.0%
==> Cloning https://github.com/randomplum/gtkwave.git
Updating /Users/cab/Library/Caches/Homebrew/gtkwave--git
==> Checking out branch formula
Already on 'formula'
Your branch is up to date with 'origin/formula'.
HEAD is now at 6b7dd45 Remove support for the AET2 format
==> Installing gtkwave from randomplum/gtkwave
==> Patching
==> Applying macos_compat.diff
patching file meson.build
patching file 'src/cocoa/cocoa_misc.c'
patching file 'src/cocoa/cocoa_misc.h'
patching file 'src/main.c'
patching file 'src/meson.build'
patching file 'src/wave_view.c'
==> meson setup build
==> meson compile -C build --verbose
==> meson install -C build
🍺  /opt/homebrew/Cellar/gtkwave/HEAD-6b7dd45_2: 69 files, 4.3MB, built in 12 seconds
==> Running `brew cleanup gtkwave`...
Disable this behaviour by setting HOMEBREW_NO_INSTALL_CLEANUP.
Hide these hints with HOMEBREW_NO_ENV_HINTS (see `man brew`).
Removing: /Users/cab/Library/Caches/Homebrew/gtkwave--patch--7f5f50dd6c1e25a6d0d5b8f05ca9f32ef650a30bff2fa128086b3daa7ad19dd2.diff... (6KB)
```

however when i try to run gtkwave, i get the following error:
```
$ gtkwave

GTKWave Analyzer v3.4.0 (w)1999-2022 BSI

GTKWAVE | Use the -h, --help command line flags to display help.

(gtkwave:56167): Gtk-CRITICAL **: 14:55:28.578: gtk_window_add_accel_group: assertion 'GTK_IS_WINDOW (window)' failed
```
 
 I will look into the code here if I find the time today. The formulae is just me looking at this quick. I could be mistaken completely.
 
 I appreciate what your are doing here. Thank you.

**Comment by 21st-centuryman** [comment] 2023-10-03 12:56
Also want to mention, when I check my applications folder I also see nothing, if this is relevant

**Comment by randomplum** [comment] 2023-10-03 13:25
Gtk-Criticals are fixed in the upstream repo, but until all the patches are merged I'll not update. This error should not interfere with operation, or does it creating some issues for you?
Currently the formula does not generate an app package needs to be started with a binary directly. 
There is no cask since there is no release that supports macos at this point. I'm working on getting the gtkwave macos ready for 3.4.0 release, but it's still some weeks away, until then we're stuck with HEAD only formula, sorry.

**Comment by 21st-centuryman** [comment] 2023-10-03 13:42
Ok thank you for your quick response. 

And thank you for working on this.

its mainly my fault for deciding to update my mac while i still had to use this software for school, but I do have VMs as a backup.

I wish you the best of luck with this release, if there is anything i can help with or you get busy with other stuff. just send me a message here. I hope you have a great rest of your week

**Comment by randomplum** [comment] 2023-10-03 13:47
@21st-centuryman Thanks for reporting, the more testing we do, the more bugs get squashed. For example turns out that most of the graphical bugs were reproducible on other platforms so in the end testing on macos improved GTKWave for everyone.  
So please use it when you can and report all the broken things.


Have a nice day!

**Closed as completed by randomplum** 2023-10-03 13:47 UTC
